### ISSUE TITLE
Failed to load plug-ins config schema

### ISSUE THREAD

**Issue by isesh** [richierockskool/homebridge-inkbird-wifi-gateway#15]
![IMG_0334](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/assets/133433851/d452700e-8daf-4dc0-b97e-381a052ab6fd)

**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by burtherman** [comment]
Same issue

**Comment by sebaslag** [comment]
Same

**Comment by richierockskool** [comment]
A new push is coming soon, and it has corrected "Failed to load plugin's Config Schema

**Comment by richierockskool** [comment]
try      npm install -g homebridge-inkbird-wifi-gateway@1.2.1

Adjustments to Config Schema are coming soon to make it work properly, thank you for your patience

**Comment by sebaslag** [comment]
> try npm install -g homebridge-inkbird-wifi-gateway@1.2.1
> 
> Adjustments to Config Schema are coming soon to make it work properly, thank you for your patience

Oh it works now nice work! But it does not add an accessory. Maybe because I have an IBS_M2

**Comment by richierockskool** [comment]
No it will work with all Inkbird Wifi Gateways soon, I am trying to get the IP address function to work correctly and you should be able connect the Gateway vis the IP and get the information on each sensor you have  in HomeKit just like the app.
