### ISSUE TITLE
Installation on HOOBS get stuck

### ISSUE THREAD

**Issue by Hedrakk** [richierockskool/homebridge-inkbird-wifi-gateway#7]
Hi, 

I really don’t know much about how things are working when you install a plug-in in either HOOBS or any other HomeBridge service, but I have installed a lot of plug-ins and they were all installed fine, but yours get stuck in the installation process. 

I hope you’ll be able to help, I’m really looking forward to use your plug-in. 

Thanks

![23DC0461-27F7-4A05-9A33-7AB347D90D12](https://user-images.githubusercontent.com/45838718/179534131-423e6641-7ab8-40c3-af1e-9ee860f05dd6.png)

![F90DF253-F4C1-4F8D-A206-655432400EFC](https://user-images.githubusercontent.com/45838718/179534184-cd56cdae-6a98-47a4-aeeb-99fb742fafb1.png)

**Comment by richierockskool** [comment]
That is the issue we are trying to fix, the plugin file is there. We need a pro input to get through this.

**Comment by Hedrakk** [comment]
This is the comment I got from an “Expert” on the HOOBS Facebook page:

“make sure you are up to date, should be on Hoobs v4.2.8 / Node 16.16.0 / Homebridge 1.5.0

the dev might be using too old npm? not really sure but might something they need to correct on their end”

**Comment by Hedrakk** [comment]
Any luck yet getting it to work?

I don't know if it would be of any help but I got that once or two when I was trying to install your plugin...
![2022-07-18 17_06_09-HOOBS](https://user-images.githubusercontent.com/45838718/181863525-3e865173-19b5-46d8-8300-1852d7b8a2c9.png)

**Comment by ShaunRoberts543** [comment]
Having same issue with Homebridge.  It will start to install plug-in, then just freezes and I have to refresh my connection and it was not installed.

**Comment by richierockskool** [comment]
There is still an error in the scrip somewhere not allowing the platform to find the plugin. We are still trying to find out why.

**Comment by Hedrakk** [comment]
Happy to see that we're getting closer to have your nice plugin!

That being said, here's what I'm getting now, with version 1.0.9

![image](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/assets/45838718/91b7d78f-af1b-4f7a-a7f8-1b830806da27)

I really don't know if this will help as I'm just a "Dumb" user. Let hope you'll be able to give us a working plugin for this new swimming pool season. Thanks!
